# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax
name: "Validate PR"

on:  # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:

  ###########################################################
  build:
  ###########################################################
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write


    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit


      - name: "Validate semantic PR title"
        # https://github.com/amannn/action-semantic-pull-request
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # https://mazer.dev/en/git/best-practices/git-semantic-commits/
          # https://github.com/commitizen/conventional-commit-types/blob/master/index.json
          types: |
            build
            ci
            chore
            docs
            fix
            feat
            refact
            revert
            perf
            style
            test
          scopes: |
            [a-z]+[a-z0-9-]*
          requireScope: false


      - name: "Label PR"
        # https://github.com/srvaroa/labeler
        uses: srvaroa/labeler@bf262763a8a8e191f5847873aecc0f29df84f957 # v1.14.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
